export const companyInitialValues = {
    profileImage:null,
    companyName: '',
    email: '',
    phoneNumber1: '',
    phoneNumber2: '',
    fax: '',
    website: '',
    owner: '',
    tags: '',
    deals: {},
    industry: '',
    contact: '',
    currency: '',
    language: '',
    aboutCompany: '',
    primaryAddress: '',
    secondaryAddress: '',
    city: '',
    state: '',
    country: '',
    zipCode: '',
    facebook: '',
    twitter: '',
    linkedin: '',
    instagram: '',
    youtube: '',
};